config/routes.rb
Rails.application.routes.draw do
  
  resources :konfirmasi_displays do
    member do
      patch :checked_status
    end
  end
  resources :plan_visits
  #planning orders
  get 'order/production/planning/aging_orders'

  namespace :api do
    namespace :v1 do
      post '/normal' => 'stocks#stock_normal'
      post '/car' => 'stocks#car_insert_pos1'
    end

    devise_scope :user do
      post '/sessions' => 'sessions#create'
    end

    resources :sessions
  end

  resources :indonesia_cities
  resources :salesmen
  devise_for :users
  # defaults to dashboard
  root :to => 'pages#template'

  # view routes

  # market share
  resources :marketshares do
    collection do
      get 'by_store'
    end
  end

  # Sales Productivity
  resources :sales_productivities do
    collection do
      get 'upload_rkb'
      post 'import'
    end
  end
  
  # Asong
  get 'asong/report_by_branch'
  
  #data source
  get 'forecasts/dash_sales'
  get 'sources/budget'
  get 'sources/sales_report'
  get 'sources/item_ledger'
  get 'sources/sold_as_order'
  get 'sources/upload_forecast'
  post 'sources/import'
  post 'sources/import_weekly'
  post 'sources/import_target_sales'
  post 'sources/import_rkb'

  # FORECAST
  get 'forecasts/management_forecast_by_sales'
  get 'forecasts/management_forecast_by_bom'
  get 'forecasts/management_forecast_by_branch'
  get 'forecasts/management_forecast_by_brand'
  get 'forecasts/akurasi_forecast_sales'
  get 'forecasts/score_card'
  get 'forecasts/score_card_salesman'
  get 'forecasts/nasional_aging_stock'
  get 'forecasts/customer_prog'
  get 'forecasts/report_rkb'
  get 'forecasts/report_pbjm'
  get 'forecasts/report_pbjm_cabang'
  get 'forecasts/rkm_sales_page'
  get 'forecasts/rekap_report_rkm'
  get 'forecasts/report_rkm'
  get 'forecasts/pbjm_cabang'
  get 'forecasts/report_forecasts_branches'
  get 'forecasts/report_forecasts_salesman'
  get 'forecasts/report_forecasts_items'
  get 'forecasts/export_all_forecast'
  get 'forecasts/report_forecasts_years'
  get 'forecasts/report_forecasts_directs'
  get 'sales_form/sales_form'

  #SUCCESS RATE ALL BRANCH
  get 'rates/index'

  # base price
  get 'base_prices/first_regional_base_prices/elite'
  get 'base_prices/first_regional_base_prices/lady'
  get 'base_prices/first_regional_base_prices/serenity'
  get 'base_prices/first_regional_base_prices/royal'
  get 'base_prices/first_regional_base_prices/base_price_mattress'
  get 'base_prices/first_regional_base_prices/base_price_divan'
  get 'base_prices/first_regional_base_prices/base_price_sorong'
  get 'base_prices/first_regional_base_prices/base_price_foam'
  get 'base_prices/second_regional_base_prices/elite'
  get 'base_prices/second_regional_base_prices/lady'
  get 'base_prices/second_regional_base_prices/serenity'
  get 'base_prices/second_regional_base_prices/royal'
  get 'base_prices/third_regional_base_prices/elite'
  get 'base_prices/third_regional_base_prices/lady'
  get 'base_prices/third_regional_base_prices/serenity'
  get 'base_prices/third_regional_base_prices/royal'
  get 'base_prices/fourth_regional_base_prices/elite'
  get 'base_prices/fourth_regional_base_prices/lady'
  get 'base_prices/fourth_regional_base_prices/serenity'
  get 'base_prices/fourth_regional_base_prices/royal'
  get 'base_prices/second_regional_base_prices/base_price_mattress'
  get 'base_prices/third_regional_base_prices/base_price_mattress'
  get 'base_prices/fourth_regional_base_prices/base_price_mattress'

  # salesman
  get 'penjualan_salesman/elite'
  get 'penjualan_salesman/lady'
  get 'penjualan_salesman/serenity'
  get 'penjualan_salesman/royal'
  get 'penjualan_salesman/weekly'
  get 'penjualan_salesman/monthly'
  
  #Royal 2
  get 'stock/royal_dua/stock_royal/stock_normal'
  get 'stock/royal_dua/stock_royal/stock_fiber'
  
  #Royal 3
  get 'stock/royal_tiga/stock_elite/stock_ba'
  get 'stock/royal_tiga/stock_elite/stock_sa'

  #Nasional MODERN
  get 'penjualan/nasional/nasional_channels/all_channel'
  get 'penjualan/nasional/nasional_customers/national_customer'
  get 'penjualan_modern/nasional/nasional_elites/daily'
  get 'penjualan_modern/nasional/nasional_elites/weekly'
  get 'penjualan_modern/nasional/nasional_elites/monthly'
  get 'penjualan_modern/nasional/nasional_lady/daily'
  get 'penjualan_modern/nasional/nasional_lady/weekly'
  get 'penjualan_modern/nasional/nasional_lady/monthly'
  get 'penjualan_modern/nasional/nasional_serenity/daily'
  get 'penjualan_modern/nasional/nasional_serenity/weekly'
  get 'penjualan_modern/nasional/nasional_serenity/monthly'
  get 'penjualan_modern/nasional/nasional_royal/daily'
  get 'penjualan_modern/nasional/nasional_royal/weekly'
  get 'penjualan_modern/nasional/nasional_royal/monthly'

  #Nasional DIRECT
  get 'penjualan/nasional/nasional_channels/all_channel'
  get 'penjualan/nasional/nasional_customers/national_customer'
  get 'penjualan_direct/nasional/nasional_elites/daily'
  get 'penjualan_direct/nasional/nasional_elites/weekly'
  get 'penjualan_direct/nasional/nasional_elites/monthly'
  get 'penjualan_direct/nasional/nasional_lady/daily'
  get 'penjualan_direct/nasional/nasional_lady/weekly'
  get 'penjualan_direct/nasional/nasional_lady/monthly'
  get 'penjualan_direct/nasional/nasional_serenity/daily'
  get 'penjualan_direct/nasional/nasional_serenity/weekly'
  get 'penjualan_direct/nasional/nasional_serenity/monthly'
  get 'penjualan_direct/nasional/nasional_royal/daily'
  get 'penjualan_direct/nasional/nasional_royal/weekly'
  get 'penjualan_direct/nasional/nasional_royal/monthly'
  get 'penjualan_direct/nasional_ecom/nasional_elites/daily'
  get 'penjualan_direct/nasional_ecom/nasional_lady/daily'
  get 'penjualan_direct/nasional_ecom/nasional_serenity/daily'
  get 'penjualan_direct/nasional_ecom/nasional_royal/daily'

  #Nasional
  get 'penjualan/nasional/nasional_lady/customer_progress'
  get 'penjualan/nasional/nasional_serenity/customer_progress'
  get 'penjualan/nasional/nasional_royal/customer_progress'
  get 'penjualan/nasional/nasional_tote/customer_progress'
  get 'penjualan/nasional/nasional_elites/customer_progress'
  get 'penjualan/nasional/nasional_channels/all_channel'
  get 'penjualan/nasional/nasional_customers/national_customer'
  get 'penjualan/nasional/nasional_elites/customer_decrease'
  get 'penjualan/nasional/nasional_elites/daily'
  get 'penjualan/nasional/nasional_elites/weekly'
  get 'penjualan/nasional/nasional_elites/monthly'
  get 'penjualan/nasional/nasional_lady/customer_decrease'
  get 'penjualan/nasional/nasional_lady/daily'
  get 'penjualan/nasional/nasional_lady/weekly'
  get 'penjualan/nasional/nasional_lady/monthly'
  get 'penjualan/nasional/nasional_serenity/customer_decrease'
  get 'penjualan/nasional/nasional_serenity/daily'
  get 'penjualan/nasional/nasional_serenity/weekly'
  get 'penjualan/nasional/nasional_serenity/monthly'
  get 'penjualan/nasional/nasional_royal/customer_decrease'
  get 'penjualan/nasional/nasional_royal/daily'
  get 'penjualan/nasional/nasional_royal/weekly'
  get 'penjualan/nasional/nasional_royal/monthly'
  get 'penjualan/nasional/nasional_tote/customer_decrease'
  get 'penjualan/nasional/nasional_tote/daily'
  get 'penjualan/nasional/nasional_tote/weekly'
  get 'penjualan/nasional/nasional_tote/monthly'

  get 'stock/img/stock_pos/stock'
  #Pusat
  get 'stock/pusat_bcp/stock_capacities/capacity'
  get 'stock/pusat_bcp/stock_elite/stock_classic'
  get 'stock/pusat_bcp/stock_elite/stock_tote'
  get 'stock/pusat_bcp/stock_elite/stock_recap'
  get 'stock/pusat_bcp/stock_elite/stock_normal'
  get 'stock/pusat_bcp/stock_serenity/stock_recap'
  get 'stock/pusat_bcp/stock_serenity/stock_normal'
  get 'stock/pusat_bcp/stock_lady/stock_recap'
  get 'stock/pusat_bcp/stock_lady/stock_normal'
  get 'stock/pusat_bcp/stock_royal/stock_recap'
  get 'stock/pusat_bcp/stock_royal/stock_normal'
  get 'stock/pusat/stock_capacities/capacity'
  get 'stock/pusat/stock_elite/stock_classic'
  get 'stock/pusat/stock_elite/stock_tote'
  get 'stock/pusat/stock_elite/stock_recap'
  get 'stock/pusat/stock_elite/stock_normal'
  get 'stock/pusat/stock_elite/stock_unnormal'
  get 'stock/pusat/stock_elite/stock_clearence'
  get 'stock/pusat/stock_elite/stock_service'
  get 'stock/pusat/stock_elite/stock_display'
  get 'stock/pusat/stock_serenity/stock_recap'
  get 'stock/pusat/stock_serenity/stock_normal'
  get 'stock/pusat/stock_serenity/stock_unnormal'
  get 'stock/pusat/stock_serenity/stock_clearence'
  get 'stock/pusat/stock_serenity/stock_service'
  get 'stock/pusat/stock_serenity/stock_display'
  get 'stock/pusat/stock_lady/stock_recap'
  get 'stock/pusat/stock_lady/stock_normal'
  get 'stock/pusat/stock_lady/stock_unnormal'
  get 'stock/pusat/stock_lady/stock_clearence'
  get 'stock/pusat/stock_lady/stock_service'
  get 'stock/pusat/stock_lady/stock_display'
  get 'stock/pusat/stock_royal/stock_recap'
  get 'stock/pusat/stock_royal/stock_normal'
  get 'stock/pusat/stock_royal/stock_unnormal'
  get 'stock/pusat/stock_royal/stock_clearence'
  get 'stock/pusat/stock_royal/stock_service'
  get 'stock/pusat/stock_royal/stock_display'

  #Bestari
  get 'stock/bestari/stock_capacities/capacity'
  get 'stock/bestari/stock_elite/stock_classic'
  get 'stock/bestari/stock_elite/stock_tote'
  get 'stock/bestari/stock_elite/stock_recap'
  get 'stock/bestari/stock_elite/stock_normal'
  get 'stock/bestari/stock_elite/stock_clearence'
  get 'stock/bestari/stock_elite/stock_service'
  get 'stock/bestari/stock_elite/stock_display'
  get 'stock/bestari/stock_serenity/stock_recap'
  get 'stock/bestari/stock_serenity/stock_normal'
  get 'stock/bestari/stock_serenity/stock_clearence'
  get 'stock/bestari/stock_serenity/stock_service'

app/models/plan_visit.rb
class PlanVisit < ApplicationRecord
  has_many :customer_plan_visits, inverse_of: :plan_visit, dependent: :destroy
  accepts_nested_attributes_for :customer_plan_visits, allow_destroy: true
  
  validates_associated :customer_plan_visits
  validate :customer_must_be_fill, on: :create
  
  def customer_must_be_fill
    errors.add(:base, "Silahkan Isi Customer") if self.customer_plan_visits.empty?
  end
  
  def reject_customers(attributes)
    attributes['customer'].blank?
  end
  
  before_save do
    self.branch_id = Salesman.find(self.sales_id).branch_id
  end
  
  def self.index_all(date, user)
    month = date.nil? ? Date.today.month : date[:month]
    year = date.nil? ? Date.today.year : date[:year]
    plan_visit_index = user.branch1.present? ? PlanVisit.where("MONTH(date_visit) = ? AND YEAR(date_visit) = ? 
    AND branch_id = ?", month, year, user.branch1) : PlanVisit.where("MONTH(date_visit) = ? AND YEAR(date_visit) = ?",
    month, year)
    return plan_visit_index
  end
end

app/controllers/plan_visits_controller.rb
class PlanVisitsController < ApplicationController
  before_action :set_plan_visit, only: [:show, :edit, :update, :destroy]

  # GET /plan_visits
  # GET /plan_visits.json
  def index
    @plan_visits = PlanVisit.index_all(params[:date], current_user)
  end

  # GET /plan_visits/1
  # GET /plan_visits/1.json
  def show
  end

  # GET /plan_visits/new
  def new
    @plan_visit = PlanVisit.new
    @plan_visit.customer_plan_visits.build
    @customer = Customer.where("i_class = 'RET'").group(:name)
    @salesman = current_user.branch1.present? ?
      PlanVisit.find_by_sql("SELECT nama, id FROM salesmen
      WHERE branch_id = '#{current_user.branch1}' ORDER BY nama ASC") : 
      PlanVisit.find_by_sql("SELECT nama, id FROM salesmen ORDER BY nama ASC")
    @brand = PlanVisit.find_by_sql("SELECT jde_brand, id FROM tbbjmerk")
  end

  # GET /plan_visits/1/edit
  def edit
    @salesman = Salesman.find(@sales_productivity.salesmen_id)
    @customer = Customer.where("i_class = 'RET'").group(:name)
  end

  # POST /plan_visits
  # POST /plan_visits.json
  def create
    @plan_visit = PlanVisit.new(plan_visit_params)

    respond_to do |format|
      if @plan_visit.save
        format.html { redirect_to plan_visits_path, notice: "Sales productivity sukses dibuat" }
        format.json { render :show, status: :created, location: @plan_visit }
      else
        format.html { redirect_to new_plan_visit_path, flash: {alert: "Pembuatan Gagal. Isi Customer atau cek kembali inputan anda"} }
      end
    end
  end

  # PATCH/PUT /plan_visits/1
  # PATCH/PUT /plan_visits/1.json
  def update
    respond_to do |format|
      if @plan_visit.update(plan_visit_params)
        format.html { redirect_to @plan_visit, notice: 'Plan visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan_visit }
      else
        format.html { render :edit }
        format.json { render json: @plan_visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plan_visits/1
  # DELETE /plan_visits/1.json
  def destroy
    @plan_visit.destroy
    respond_to do |format|
      format.html { redirect_to plan_visits_url, notice: 'Plan visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan_visit
      @plan_visit = PlanVisit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_visit_params
      params.require(:plan_visit).permit(:sales_id, :brand, :city, :date_visit, 
      :hotel, :accomodation, :allowance, :branch_id,
      customer_plan_visits_attributes: [:call_visit, :customer, :_destroy])
    end
end

app/helpers/plan_visits_helper.rb
module PlanVisitsHelper
end

app/views/plan_visits/_customer_plan_visit.html.erb
<tr>
  <td><%= f.text_field :customer, data: { cus_source: @customer.order(:name).map(&:name)} %></td>
  <td><%= f.select :call_visit, [["call", "call"], ["visit", "visit"]], :prompt => '-select-' %></td>
  <td>
    <%= f.hidden_field :_destroy %>
    <%= link_to 'Delete', '#', class: 'remove_record' %>
  </td>
</tr>

app/views/plan_visits/_form.html.erb
<div class="row">
  <div class="panel panel-info">
    <div class="panel-heading">
      Form Rencana Kerja Bulanan
    </div>
    <div class="panel-body">
      <div class="row">
        <%= form_for(plan_visit, {:class => "form-horizontal"}) do |f| %>
        <% if plan_visit.errors.any? %>
        <div id="error_explanation">
          <h4>Not Saved. Click <%= link_to "this", new_sales_productivity_path %> for a new productivity
          or fill correctly Form Below </h4>

          <ul>
            <% plan_visit.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <% if f.object.sales_id == 0 %>
        <fieldset>
          <div class="form-group">
            <label class="col-lg-2 control-label">NAMA</label>
            <div class="col-lg-10">
              <%= f.select "sales_id", options_for_select(@salesman.map {|a| [a.nama, a.id]}), class: 'form-control' %>
            </div>
          </div>
        </fieldset>
        <fieldset>
          <div class="form-group">
            <label class="col-lg-2 control-label">BRAND</label>
            <div class="col-lg-10">
              <%= f.select "brand", options_for_select(@brand.map {|a| [a.jde_brand, a.jde_brand]}), class: 'form-control m-b' %>
            </div>
          </div>
        </fieldset>
        <fieldset>
          <div class="form-group mb">
            <label class="col-sm-2 control-label mb">DATE</label>
            <div class="col-sm-5">
              <div id="datepicker1" class="input-group date">
                <%= f.text_field "date_visit", class: 'form-control' %>
                <span class="input-group-addon"> <span class="fa fa-calendar"></span> </span>
              </div>
            </div>
          </div>
        </fieldset>
        <% else %>
        <fieldset>
          <div class="form-group">
            <label class="col-lg-2 control-label">NAMA</label>
            <div class="col-lg-10">
              <%= f.text_field "salesmen_id", value: @salesman.nama, disabled: true, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-2 control-label">BRAND</label>
            <div class="col-lg-10">
              <%= f.text_field "brand", value: f.object.brand, disabled: true, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-2 control-label">DATE</label>
            <div class="col-lg-10">
              <%= f.text_field "date", value: f.object.created_at.strftime("%d %B %Y"), disabled: true, class: 'form-control' %>
            </div>
          </div>
        </fieldset>
        <% end %>
        
        <fieldset>
          <div class="col-lg-4 col-lg-offset-3">
            <table class='table'>
              <thead>
                <tr>
                  <th>Customer</th>
                  <th></th>
                </tr>
              </thead>
              <tbody class='fields'>
                <%= f.fields_for :customer_plan_visits do |builder| %>
                  <%= render 'customer_plan_visit', f: builder %>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="col-lg-4 col-lg-offset-7">
            <%= link_to_add_row('Add', f, :customer_plan_visits, class: 'btn btn-primary') %>
          </div>
        </fieldset>
        
        <% if f.object.new_record? %>
          <%= f.submit "CREATE", class: "btn btn-primary" %>
          <%= link_to "BACK", plan_visits_path, class: "btn" %>
        <% else %>
          <%= button_to "UPDATE", plan_visits_path(:id => f.object.id),
        method: :put, class: "btn btn-primary" %>
          <%= link_to "BACK", plan_visits_path, class: "btn" %>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/plan_visits/edit.html.erb
<h1>Editing Plan Visit</h1>

<%= render 'form', plan_visit: @plan_visit %>

<%= link_to 'Show', @plan_visit %> |
<%= link_to 'Back', plan_visits_path %>

app/views/plan_visits/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Search by Month Form
  </div>
  <div class="panel-body">
    <%= form_tag(request.fullpath, {method: :get, :class => "form-inline"}) do %>
    <div class="form-group">
      <%= select_month(params[:date].present? ? params[:date][:month].to_i : Date.today.month, {prompt: 'Choose month'}, class: "form-control") %>
    </div>
    <div class="form-group">
      <%= select_year(Date.today, {start_year: 2017, end_year: Date.today.year, prompt: 'Choose year'}, {class: "form-control"}) %>
    </div>
    <%= submit_tag 'Search', name: nil, class: "btn btn-info" %>
    <% end %>
  </div>
</div>

<div class="row">
  <!-- START dashboard main content-->
  <div class="col-lg-12">
    <div class="row">
      <div class="panel panel-info">
        <div class="panel-heading">
          Rencana Kerja Bulanan
        </div>
        <div class="panel-body">
          <table id="productivities" class="table table-striped table-hover">
            <thead>
              <tr>
                <th>Sales</th>
                <th>Branch</th>
                <th>Brand</th>
                <th>Date visit</th>
                <th colspan="2"></th>
              </tr>
            </thead>
            <tfoot></tfoot>
            <tbody>
              <% @plan_visits.each do |sm| %>
              <tr>
                <td><%= find_sales(sm.sales_id).nama %></td>
                <td><%= find_branch(sm.branch_id) %></td>
                <td><%= sm.brand %></td>
                <td><%= sm.date_visit.strftime("%d %B %Y") %></td>
                <td><%= link_to 'Edit', edit_plan_visit_path(sm) %></td>
                <td><%= link_to 'Destroy', sm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="panel-footer">
          if you want to create a new one? click <%= link_to "here", new_plan_visit_path, class: "mb-sm btn-xs btn btn-primary btn-outline" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/plan_visits/new.html.erb
<%= render 'form', plan_visit: @plan_visit %>

app/views/plan_visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sales:</strong>
  <%= @plan_visit.sales_id %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @plan_visit.brand %>
</p>

<p>
  <strong>City:</strong>
  <%= @plan_visit.city %>
</p>

<p>
  <strong>Date visit:</strong>
  <%= @plan_visit.date_visit %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @plan_visit.customer %>
</p>

<p>
  <strong>Hotel:</strong>
  <%= @plan_visit.hotel %>
</p>

<p>
  <strong>Accomodation:</strong>
  <%= @plan_visit.accomodation %>
</p>

<p>
  <strong>Allowance:</strong>
  <%= @plan_visit.allowance %>
</p>

<%= link_to 'Edit', edit_plan_visit_path(@plan_visit) %> |
<%= link_to 'Back', plan_visits_path %>